# Generated by Django 4.1.1 on 2022-09-22 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catagory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
            options={"verbose_name": "Category", "verbose_name_plural": "Categories",},
        ),
        migrations.CreateModel(
            name="TodoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("content", models.CharField(blank=True, max_length=300)),
                ("created", models.DateField(default="2022-09-22")),
                ("due_date", models.DateField(default="2022-09-22")),
                (
                    "category",
                    models.ForeignKey(
                        default="general",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app123.catagory",
                    ),
                ),
            ],
            options={"ordering": ["-created"],},
        ),
    ]
